--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:Tout',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:ChSetPointRB',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:PexpV',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:Pref_hp',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:Pref_lp',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:Tevap',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:TexpV',1,1,9999);
--
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:RelayStatus1_Alarm',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:RelayStatus1_WaterPump',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val) VALUES ( 'DQ:CHL:RelayStatus2_CondensingFan',1,1,9999);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:CompWH',1,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:WaterPumpWH',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm1',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm2',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm3',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm4',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm5',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm6',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm7',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm8',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm9',2,1,9999,1);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:CHL:Alarm10',2,1,9999,1);

--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:THe',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:TOil',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:TcoolIn',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:TcoolOut',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:p1',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:p2',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:p3',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:p4',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:p5',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:p6',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:t4k',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:t50k',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:tmixing',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:tstill',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v1',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v10',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v11',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v12',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v13',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v14',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v15',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v16',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v17',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v18',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v19',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v2',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v20',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v21',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v22',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v3',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v4',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v5',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v6',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v7',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v8',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:v9',1,1,9999,10);

--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCCH:ch7_r',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCCH:ch7_t',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCCH:ch8_r',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCCH:ch8_t',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:flow',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:compressor',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:scroll1',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:scroll2',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:turbo1',1,1,9999,10);

--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:Phigh',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:Plow',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:THe_C',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:TOil_C',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:TcoolIn_C',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:CPA:TcoolOut_C',1,1,9999,10);
--
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:4kHeater',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:hsExt',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:hsMC',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:hsStill',1,1,9999,10);

-- INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:MPBF:pulsetube',1,1,9999,10);

--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:NXDS:controller_temperature_C',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:NXDS:pump_temperature_C',1,1,9999,10);
--INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:NXDS:rotational_frequency',1,1,9999,10);

INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCHT:ht1_pw',1,1,9999,10);
INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCHT:ht2_pw',1,1,9999,10);
INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCHT:ht3_pw',1,1,9999,10);
INSERT INTO channel(name,smpl_mode_id,grp_id,retent_val,smpl_per) VALUES ( 'DQ:BF:TCHT:ht4_pw',1,1,9999,10);

--UPDATE channel SET smpl_per=1 WHERE channel_id < 100;
--UPDATE channel SET smpl_mode_id=2 WHERE channel_id < 100;
--UPDATE channel SET grp_id=1 WHERE channel_id < 100;
--UPDATE channel SET retent_val=9999 WHERE channel_id < 100;
--UPDATE channel SET name=Pcir1 WHERE channel_id < 8;
--DELETE FROM channel where channel_id = 9;
--DELETE FROM sample where channel_id = 9;
