# Channel access
org.phoebus.pv/default=ca

org.phoebus.pv.ca/addr_list=127.0.0.1
org.phoebus.pv.ca/auto_addr_list="false"
org.phoebus.pv.ca/max_array_bytes=1000000

org.phoebus.pv.pva/epics_pva_addr_list=127.0.0.1
org.phoebus.pv.pva/epics_pva_auto_addr_list="false

# Archiver
org.csstudio.trends.databrowser3/trace_type=SINGLE_LINE

#org.csstudio.trends.databrowser3/urls=pbraw\://127.0.0.1:17668/retrieval
#org.csstudio.trends.databrowser3/archives=pbraw\://127.0.0.1:17668/retrieval
# org.csstudio.trends.databrowser3/urls=jdbc:mysql://localhost/archive|RDB*xnds://localhost/archive/cgi/ArchiveDataServer.cgi
# org.csstudio.trends.databrowser3/archives=jdbc:mysql://localhost/archive|RDB*xnds://localhost/archive/cgi/ArchiveDataServer.cgi
#org.csstudio.trends.databrowser3/urls=jdbc:postgresql://localhost:5432/archive
#org.csstudio.trends.databrowser3/archives=jdbc:postgresql://localhost:5432/archive

org.csstudio.trends.databrowser3/urls=jdbc:postgresql://localhost:5432/archive|Archiver
org.csstudio.trends.databrowser3/archives=jdbc:postgresql://localhost:5432/archive|Archiver
#
#

########################################
# Package org.phoebus.archive.reader.rdb
########################################

org.phoebus.archive.reader.rdb/user=report
org.phoebus.archive.reader.rdb/password=$report
#org.phoebus.archive.reader.rdb/prefix=
#org.phoebus.archive.reader.rdb/timeout_secs=120
#org.phoebus.archive.reader.rdb/use_array_blob=true
#org.phoebus.archive.reader.rdb/stored_procedure=
#org.phoebus.archive.reader.rdb/starttime_function=
#org.phoebus.archive.reader.rdb/fetch_size=1000
#org.phoebus.archive.reader.rdb/equivalent_pv_prefixes=ca, pva

#################################
# Package org.csstudio.archive.ts
#################################

#org.csstudio.archive.ts/user=report
#org.csstudio.archive.ts/password=$report
#org.csstudio.archive.ts/timeout_secs=120
#org.csstudio.archive.ts/fetch_size=1000

#################################
# Package org.csstudio.archive
#################################

org.csstudio.archive/url=jdbc:postgresql://localhost:5432/archive
org.csstudio.archive/user=archive
org.csstudio.archive/password=$archive


# AlarmServer
#org.phoebus.applications.alarm/server=PLAINTEXT://localhost:9092
#org.phoebus.applications.alarm/server=127.0.0.1:9092

# Alarm Logging
#org.phoebus.applications.alarm.logging.ui/service_uri = http://127.0.0.1:8080
#org.phoebus.applications.alarm.logging.ui/results_max_size = 10000

# Channel Finder (Changed to port 8081)
#org.phoebus.channelfinder/serviceURL=http://localhost:8081/ChannelFinder

# Save and Restore (Changed to port 8082
#org.phoebus.applications.saveandrestore/jmasar.service.url=http://localhost:8082/save-restore

