<?xml version="1.0" encoding="UTF-8"?>
<databrowser>
  <title></title>
  <show_legend>true</show_legend>
  <show_toolbar>true</show_toolbar>
  <grid>true</grid>
  <update_period>5.0</update_period>
  <scroll_step>5</scroll_step>
  <scroll>true</scroll>
  <start>-20 minutes -45.536 seconds</start>
  <end>now</end>
  <archive_rescale>NONE</archive_rescale>
  <foreground>
    <red>0</red>
    <green>0</green>
    <blue>0</blue>
  </foreground>
  <background>
    <red>255</red>
    <green>255</green>
    <blue>255</blue>
  </background>
  <title_font>Liberation Sans|20|1</title_font>
  <label_font>Liberation Sans|14|1</label_font>
  <scale_font>Liberation Sans|12|0</scale_font>
  <legend_font>Liberation Sans|14|0</legend_font>
  <axes>
    <axis>
      <visible>true</visible>
      <name>Temp (K)</name>
      <use_axis_name>true</use_axis_name>
      <use_trace_names>false</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>0.0013093560793655604</min>
      <max>0.06550218852772367</max>
      <grid>true</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
  </axes>
  <annotations>
  </annotations>
  <pvlist>
    <pv>
      <display_name>DQ:BF:MPBF:t50k</display_name>
      <visible>true</visible>
      <name>DQ:BF:MPBF:t50k</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <trace_type>SINGLE_LINE</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>500</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>Archiver</name>
        <url>jdbc:postgresql://localhost:5432/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>DQ:BF:MPBF:t4k</display_name>
      <visible>true</visible>
      <name>DQ:BF:MPBF:t4k</name>
      <axis>0</axis>
      <color>
        <red>0</red>
        <green>255</green>
        <blue>0</blue>
      </color>
      <trace_type>SINGLE_LINE</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>500</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>Archiver</name>
        <url>jdbc:postgresql://localhost:5432/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>DQ:BF:MPBF:tstill</display_name>
      <visible>true</visible>
      <name>DQ:BF:MPBF:tstill</name>
      <axis>0</axis>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>255</blue>
      </color>
      <trace_type>SINGLE_LINE</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>500</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>Archiver</name>
        <url>jdbc:postgresql://localhost:5432/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>DQ:BF:MPBF:tmixing</display_name>
      <visible>true</visible>
      <name>DQ:BF:MPBF:tmixing</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>127</green>
        <blue>0</blue>
      </color>
      <trace_type>SINGLE_LINE</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>500</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>Archiver</name>
        <url>jdbc:postgresql://localhost:5432/archive</url>
        <key>1</key>
      </archive>
    </pv>
  </pvlist>
</databrowser>
