
# Self-update
org.phoebus.applications.update/current_version=2026-08-11 23:59
org.phoebus.applications.update/update_url=https://controlssoftware.sns.ornl.gov/css_phoebus/nightly/phoebus-$(arch).zip

#Source
org.phoebus.pv/default=archive

# Archiver 
org.csstudio.trends.databrowser3/urls=pbraw\://192.168.100.102:17668/retrieval*jdbc:postgresql://192.168.100.102:5432/archive
org.csstudio.trends.databrowser3/archives=pbraw\://192.168.100.102:17668/retrieval*jdbc:postgresql://192.168.100.102:5432/archive

# org.phoebus.archive.reader.appliance/useStatisticsForOptimizedData=true
# org.phoebus.archive.reader.appliance/useNewOptimizedOperator=true
# org.phoebus.archive.reader.appliance/useHttps=false

org.phoebus.pv.archive/archive_url=http://192.168.100.102:17668/retrieval

# RDB
org.phoebus.archive.reader.rdb/user=report
org.phoebus.archive.reader.rdb/password=$report


##########################################
# Package org.csstudio.trends.databrowser3
##########################################

# org.csstudio.trends.databrowser3/use_auto_scale=false
# org.csstudio.trends.databrowser3/time_span=3600
# org.csstudio.trends.databrowser3/scan_period=0.0
# org.csstudio.trends.databrowser3/update_period=3.0
org.csstudio.trends.databrowser3/live_buffer_size=500
# org.csstudio.trends.databrowser3/line_width=2
# org.csstudio.trends.databrowser3/opacity=40
org.csstudio.trends.databrowser3/trace_type=SINGLE_LINE
# org.csstudio.trends.databrowser3/archive_fetch_delay=500
# org.csstudio.trends.databrowser3/archive_read_timeout_ms=30000
# org.csstudio.trends.databrowser3/concurrent_requests=1000
# org.csstudio.trends.databrowser3/plot_bins=-3
# org.csstudio.trends.databrowser3/use_default_archives=true
org.csstudio.trends.databrowser3/drop_failed_archives=false
# org.csstudio.trends.databrowser3/equivalent_pv_prefixes=ca, pva
org.csstudio.trends.databrowser3/archive_rescale=NONE
# org.csstudio.trends.databrowser3/time_span_shortcuts=30 Minutes,-30 min|1 Hour,-1 hour|12 Hours,-12 hour|1 Day,-1 days|7 Days,-7 days
# org.csstudio.trends.databrowser3/plt_repository=/opt/codac/opi/databrowser/
# org.csstudio.trends.databrowser3/automatic_history_refresh=true
# org.csstudio.trends.databrowser3/scroll_step = 5
# org.csstudio.trends.databrowser3/use_trace_names = true
# org.csstudio.trends.databrowser3/prompt_for_raw_data_request = true
# org.csstudio.trends.databrowser3/prompt_for_visibility = true
# org.csstudio.trends.databrowser3/time_span_shortcuts=30 Minutes,-30 min|1 Hour,-1 hour|12 Hours,-12 hour|1 Day,-1 days|7 Days,-7 days
# org.csstudio.trends.databrowser3/config_dialog_supported=false
# org.csstudio.trends.databrowser3/value_axis_label_policy=pv-name
# org.csstudio.trends.databrowser3/assign_pvs_from_clipboard_to_the_same_axis_by_default=false


